global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: cyberops-gateway
    static_configs:
      - targets: ["gateway:8000"]
  - job_name: cyberops-core
    static_configs:
      - targets: ["core:8001"]
  - job_name: cyberops-auth
    static_configs:
      - targets: ["auth:8002"]
  - job_name: cyberops-worker
    static_configs:
      - targets: ["worker:9091"]
  - job_name: cyberops-jaeger
    static_configs:
      - targets: ["jaeger:14269"]
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]