apiVersion: 1

datasources:
  - name: Prometheus
    # uid потрібен для зв'язки Jaeger->Prometheus (tracesToLogsV2)
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false